name: All

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    container:
      image: fouge/vertices:latest
      volumes:
        - ${{github.workspace}}:/home/project/

    steps:
    - name: Checkout repo and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Unit tests
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        make -C tests clean
        make -C tests all

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: make all

    - name: Alice & Bob
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        ACCOUNT_KEYS: ${{ secrets.ACCOUNT_KEYS }}
      # first copy the private key into file
      # then starts the example: Alice send 1 Algo to Bob
      run: |
        ./utils/str_to_bin.py "$ACCOUNT_KEYS" examples/unix/config/private_key.bin
        ./build/examples/unix/unix_example
